swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts:
    get:
      tags:
        - Accounts
      summary: Return a list of customer accounts
      description: API for fetching list of customer accounts
      produces:
        - application/json
      responses:
        '200':
          description: List of customer accounts
          schema:
            $ref: '#/definitions/AccountsResponse'
        '401':
          description: unauthorized
        '500':
          description: Internal Server Error
  /accounts/{idAccount}/transactions/{idTransaction}/details:
   patch:
    tags:
      - Accounts
    summary: Modify category and/or note of a transaction
    description: API for modifying the category and/or note of a transaction
    parameters:
      - name: idAccount
        in: path
        required: true
        type: string
        description: ID of the account
      - name: idTransaction
        in: path
        required: true
        type: string
        description: ID of the transaction
      - in: body
        name: body
        description: Modify category and/or note
        required: true
        schema:
          $ref: '#/definitions/UpdateTransactionRequest'
    produces:
      - application/json
    responses:
      '200':
        description: Element updated successfully
        schema:
          $ref: '#/definitions/AccountResponse'
      '400':
        description: Invalid fields or a bad request
      '401':
        description: Unauthorized
      '403':
        description: operation forbiden
      '404':
        description: Details not found
      '500':
        description: Internal server error
  /accounts/{id}/transactions:
   get:
    tags:
      - Accounts
    summary: Get transactions of an provided account ID
    description: API for retrieving all transactions from the account by ID
    produces:
      - application/json
    parameters:
      - name: id
        in: path
        required: true
        type: string
        description: ID of the account
      - in: query
        name: month
        type: string
        description: the month to load (format YYYY-mm)
    responses:
      '200':
        description: List of transactions for the specified account
        schema:
          type: array
          items:
            $ref: '#/definitions/TransactionList'
      '401':
        description: Unauthorized
      '403':
        description: operation forbiden
      '404':
        description: account not found
      '500':
        description: Internal server error
  /categories:
   get:
    tags:
      - Categories
    summary: Get a list of available categories for selection
    description: API for retrieving a dropdown list of categories with ID and label
    produces:
      - application/json
    responses:
      '200':
        description: List of categories with ID and label
        schema:
          $ref: '#/definitions/CategoryDropdownResponse'
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountsResponse:
    type: array
    items:
      $ref: '#/definitions/Account'
  Account:
    properties:
     id:
      type: number 
     amount:
      type: number
     accountNumber:
      type: string
  AccountResponse:
    type: object
    properties:
          date:
            type: string
            format: date
            description: transaction date
          description:
            type: string
            description: transaction description
          amount:
             type: number
             description: transaction amount
          balance:
             type: number
             description: transaction balance
          details:
             type: object
             properties:
              category:
                type: string
                description: transaction category
              note:
                type: string
                description: personal note
  UpdateTransactionRequest:
    type: object
    properties:
      category:
        type: string
        description: update category (optional)
      note:
        type: string
        description: update note (optional)
    required:
       - details
  CategoryDropdownResponse:
   type: array
   items:
    type: object
    properties:
      id:
        type: string
        description: TODO
      label:
        type: string
        description: TODO
   
  TransactionList:
   type: object
   properties:
    id:
      type: string
      description: Transaction ID
    date:
      type: string
      format: date
      description: Transaction date
    description:
      type: string
      description: Transaction description
    amount:
      type: number
      description: Transaction amount
    balance:
      type: number
      description: Transaction balance
    details:
      type: object
      properties:
        type:
          type: string
          description: Transaction type
        categoryId:
          type: string
          description: Transaction category ID
        note:
          type: string
          description: Personal note
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string